/**
 * Film & TV reference examples for the Narrative Engine.
 * Each entry maps field keys to example values from popular stories.
 */

export interface FilmExample {
  title: string;
  year: string;
  medium: 'film' | 'tv';
  fields: Record<string, string>;
}

export const filmExamples: FilmExample[] = [
  {
    title: 'The Matrix',
    year: '1999',
    medium: 'film',
    fields: {
      theme: 'This story proves that reality is defined by what you choose to believe, and freedom requires the courage to reject comfortable lies.',
      protag_name: 'Thomas "Neo" Anderson',
      protag_archetype: 'The Chosen One / Reluctant Hero',
      protag_flaw: 'Self-doubt — refuses to believe he\'s capable of being "The One"',
      protag_misbelief: 'He believes he\'s nobody special, just a cog in the machine, and that the rules of the world are fixed and unbreakable.',
      a_goal: 'Must learn the truth about the Matrix and defeat Agent Smith BEFORE the machines find Zion or Morpheus is killed.',
      antag_name: 'Agent Smith',
      antag_want: 'To eliminate all human resistance and escape the Matrix himself — he despises humanity and the prison he\'s trapped in.',
      antag_belief: 'Humans are a virus, a disease — the Matrix is order, and order must be preserved through total control.',
      antag_flaw: 'Obsessive need for control (mirrors Neo\'s need to break free from control).',
      a1_want: 'Neo wants to know "What is the Matrix?" — the answer to the question that haunts him.',
      a1_trigger: 'Trinity contacts him; Agents are already tracking him. It\'s now or never.',
      a1_stakes: 'If he doesn\'t act, he stays a drone forever. If he acts and fails, the machines kill him.',
      a1_inciting: 'Morpheus offers the red pill or blue pill — the choice to see reality.',
      a1_ponr: 'Neo swallows the red pill. There is no going back to ignorance.',
      b1_flaws: 'Neo is passive, anxious, and doesn\'t trust himself. He hides behind a computer screen.',
      b1_contradiction: 'Wants to be free but is terrified of responsibility.',
      b1_block: 'His inability to believe in himself prevents him from accessing his full power.',
      c1_motivation: 'Smith is a program doing his job — but he\'s grown to hate it. He wants out, just like Neo.',
      c1_understand: 'He\'s trapped in a system he despises, forced to clean up after humans. His frustration is relatable.',
      c1_believe: 'He\'s the most powerful entity in the Matrix. His threat is immediate and real.',
      c1_sympathize: 'He\'s a prisoner too — stuck in the Matrix just like the humans, but without even the illusion of choice.',
      c1_goal: 'Find the access codes to Zion\'s mainframe by breaking Morpheus.',
      a2_plan: 'Train in combat, learn the rules of the Matrix, rescue the world by becoming The One.',
      a2_win1: 'Neo masters combat training at extraordinary speed — "I know kung fu."',
      a2_win2: 'Neo begins bending the rules of the Matrix — moving faster, hitting harder.',
      a2_complication: 'The Oracle tells Neo he\'s NOT The One, shattering his fragile confidence.',
      mid_choice: 'Neo chooses to go back into the Matrix to rescue Morpheus — knowing he\'ll likely die — because Morpheus believed in him.',
      mid_change: 'The mission shifts from "become The One" to "save the man who believed in me."',
      mid_broken: 'The plan was for Morpheus to guide Neo. Now Morpheus is captured and Neo has to lead.',
      mid_impossible: 'Neo was told he\'s NOT The One. He\'s going against Agents with no prophecy backing him.',
      b2_warnings: 'Cypher\'s betrayal — someone who lost faith. A mirror of what Neo could become.',
      b2_flaw_active: 'Neo\'s self-doubt makes him hesitate in combat, nearly getting killed multiple times.',
      b2_crisis: 'He must decide if he\'s willing to die for what he believes, even without proof he\'s special.',
      c2_adapt: 'Smith captures Morpheus and begins extraction of Zion codes. The clock is ticking.',
      c2_learns: 'Smith discovers that Neo is emotionally attached to Morpheus — exploitable loyalty.',
      low_external: 'Morpheus is captured, the crew is betrayed, they\'re outgunned inside the Matrix.',
      low_internal: 'Neo has been told he\'s not The One. He has no reason to believe he can win.',
      low_finished: 'The Oracle said he wasn\'t special. His mentor is captured. The traitor won.',
      b3_revelation: '"I thought I had to be chosen. The truth is, being The One is a choice I make right now."',
      b3_decision: 'Neo stops running. He turns to face Agent Smith instead of fleeing.',
      a3_plan: 'Go back in, fight Smith head-on, rescue Morpheus through sheer will and belief.',
      a3_confrontation: 'Neo vs. Agent Smith in the subway — then resurrection and total Matrix mastery.',
      a3_risked: 'His life — literally. He\'s shot and killed.',
      a3_sacrificed: 'His old identity. Thomas Anderson dies so Neo can live.',
      c3_flaw: 'Smith\'s rigid need for control — he can\'t adapt when Neo breaks the rules entirely.',
      c3_mirror: 'Smith is trapped by his programming (control). Neo frees himself from his (doubt). Same prison, opposite choices.',
      den_truth: 'You don\'t wait to be chosen. You choose yourself. Reality bends to belief.',
      den_protag: 'Neo is fully awakened — sees the Matrix as code, unstoppable.',
      den_support: 'Trinity\'s love is validated. Morpheus\'s faith is proven right.',
      den_world: 'The Matrix is compromised. The machines now face a threat they can\'t control.',
      den_cost: 'Neo died and was reborn. His old life is gone forever.',
      fran_imbalance: 'Neo can now manipulate the Matrix at will — but Smith survived and is evolving.',
      fran_watching: 'The machine world. Other programs. The Architect.',
      fran_system: 'The Matrix is just one layer. There are deeper systems of control.',
    },
  },
  {
    title: 'The Empire Strikes Back',
    year: '1980',
    medium: 'film',
    fields: {
      theme: 'This story proves that true strength comes from confronting painful truths rather than running from them.',
      protag_name: 'Luke Skywalker',
      protag_archetype: 'The Idealist Hero',
      protag_flaw: 'Impatience and recklessness — rushes into danger without preparation.',
      protag_misbelief: 'He believes he can defeat evil through sheer willpower and that the galaxy is black and white — good vs. evil with no gray.',
      a_goal: 'Must become a Jedi and defeat the Empire BEFORE they crush the Rebellion or his friends are killed.',
      antag_name: 'Darth Vader',
      antag_want: 'To capture Luke and turn him to the Dark Side — to rule the galaxy as father and son.',
      antag_belief: 'The Dark Side is the only true path to power, and the galaxy needs order through strength.',
      antag_flaw: 'Cannot let go of attachment (mirrors Luke\'s attachment to his friends).',
      a1_want: 'The Rebellion needs to survive the Empire\'s counterattack after destroying the Death Star.',
      a1_trigger: 'Imperial probe droids discover the Rebel base on Hoth — the Empire is coming NOW.',
      a1_stakes: 'Total destruction of the Rebel Alliance.',
      a1_inciting: 'The Empire attacks Hoth. The Rebels are scattered and on the run.',
      a1_ponr: 'Luke leaves for Dagobah to train with Yoda instead of staying with the Rebellion.',
      b1_flaws: 'Luke is cocky after destroying the Death Star. He thinks he\'s already a hero.',
      b1_contradiction: 'Wants to be a Jedi but lacks the patience and humility required.',
      b1_block: 'His arrogance and emotional attachment prevent him from completing his training.',
      c1_motivation: 'Vader genuinely wants his son by his side. He lost everything to the Dark Side and sees Luke as his second chance.',
      c1_understand: 'He\'s a father who lost his family and wants it back — through the only means he knows.',
      c1_believe: 'He commands the entire Imperial fleet. His power is absolute.',
      c1_sympathize: 'Beneath the mask is a broken man who was manipulated and destroyed by the same system he now serves.',
      c1_goal: 'Capture Luke Skywalker alive.',
      mid_choice: 'Luke sees a vision of his friends in danger and leaves Dagobah before completing his training.',
      mid_change: 'The mission shifts from "become a Jedi" to "save Han and Leia."',
      mid_broken: 'Yoda explicitly warns him: he\'s not ready. But Luke\'s emotions override wisdom.',
      mid_impossible: 'He\'s half-trained, walking into a trap Vader specifically designed for him.',
      b3_revelation: '"I thought I could save everyone through strength. The truth is I\'m not ready, and my father is Darth Vader."',
      b3_decision: 'Luke chooses to fall rather than join Vader. He\'d rather die than become evil.',
      a3_confrontation: 'Luke vs. Vader in Cloud City — outmatched in every way.',
      a3_risked: 'His life, his hand, his identity.',
      a3_sacrificed: 'His innocence. His hand. His understanding of who he is.',
      c3_flaw: 'Vader\'s attachment — he can\'t kill Luke, which means he can\'t fully win.',
      c3_mirror: 'Both are driven by attachment. Luke\'s leads to recklessness, Vader\'s leads to obsession.',
      den_truth: 'The galaxy is more complex than good vs. evil. The enemy is your own blood.',
      den_protag: 'Luke is humbled, wounded, and fundamentally changed.',
      den_support: 'Han is frozen in carbonite. Leia carries the weight of loss.',
      den_world: 'The Rebellion is scattered and broken. The Empire is ascendant.',
      den_cost: 'Han is gone. Luke lost his hand and his innocence. The Rebellion is barely alive.',
    },
  },
  {
    title: 'Aliens',
    year: '1986',
    medium: 'film',
    fields: {
      theme: 'This story proves that confronting your deepest trauma — not running from it — is the only way to reclaim your life.',
      protag_name: 'Ellen Ripley',
      protag_archetype: 'The Survivor / Reluctant Warrior',
      protag_flaw: 'PTSD-driven paralysis — she\'s so traumatized she can barely function.',
      protag_misbelief: 'She believes that avoiding the threat is the safest course — that if she stays away, the nightmare can\'t reach her.',
      a_goal: 'Must survive LV-426 and destroy the alien threat BEFORE the xenomorphs kill everyone or Weyland-Yutani weaponizes them.',
      antag_name: 'The Xenomorph Queen / Carter Burke',
      antag_want: 'Queen: Protect and expand the hive. Burke: Secure alien specimens for bio-weapons division profit.',
      antag_belief: 'Burke believes corporate profit justifies human sacrifice. The Queen operates on pure survival instinct.',
      antag_flaw: 'Burke\'s greed blinds him to the danger he can\'t control (mirrors Ripley\'s fear of facing what she can\'t control).',
      a1_want: 'Ripley wants to be left alone, but the Company needs her expertise when contact is lost with LV-426.',
      a1_trigger: 'The colony on LV-426 goes silent. It\'s the same planet where Ripley\'s crew was killed.',
      a1_inciting: 'Burke and the Colonial Marines ask Ripley to return to LV-426 as an advisor.',
      a1_ponr: 'Ripley agrees to go — she\'d rather face the nightmare than let it haunt her forever.',
      b1_flaws: 'Ripley is shattered by nightmares. She has no life — just survival guilt and terror.',
      b1_contradiction: 'Wants safety but volunteers for the most dangerous mission imaginable.',
      b1_block: 'Her trauma keeps her reactive instead of proactive. She freezes when she should lead.',
      mid_choice: 'Ripley bonds with Newt — a surrogate daughter — giving her something to fight FOR, not just against.',
      mid_change: 'It\'s no longer about survival. It\'s about saving this child.',
      a3_confrontation: '"Get away from her, you bitch!" — Ripley in the power loader vs. the Queen.',
      a3_sacrificed: 'Her safety. She walks directly into the hive to save Newt.',
      den_truth: 'You don\'t overcome trauma by hiding. You overcome it by finding something worth fighting for.',
      den_protag: 'Ripley is whole again — a warrior and a mother.',
    },
  },
  {
    title: 'E.T. the Extra-Terrestrial',
    year: '1982',
    medium: 'film',
    fields: {
      theme: 'This story proves that love transcends all boundaries — species, distance, and even death.',
      protag_name: 'Elliott',
      protag_archetype: 'The Lonely Child / Innocent',
      protag_flaw: 'Emotional isolation — abandoned by his father, he\'s closed off and invisible in his own family.',
      protag_misbelief: 'He believes nobody understands him and that he\'s powerless to change his lonely existence.',
      a_goal: 'Must help E.T. phone home and return to his people BEFORE the government captures and dissects E.T.',
      antag_name: 'Keys (Government Agent)',
      antag_want: 'To capture and study E.T. for scientific and national security purposes.',
      antag_belief: 'An extraterrestrial organism must be contained and studied — it\'s his duty to protect the public.',
      antag_flaw: 'Institutional thinking overrides empathy (mirrors Elliott\'s journey toward radical empathy).',
      a1_inciting: 'Elliott discovers E.T. hiding in the backyard shed.',
      a1_ponr: 'Elliott hides E.T. in his room. He\'s now protecting an alien from the entire U.S. government.',
      b1_flaws: 'Elliott is angry, sad, and acting out because of his parents\' divorce.',
      b1_block: 'His emotional walls prevent him from connecting with anyone — until E.T.',
      b3_revelation: '"I thought I was alone and nobody cared. The truth is love is everywhere if you\'re brave enough to reach for it."',
      den_truth: 'Connection is the most powerful force in the universe. Even saying goodbye is an act of love.',
      den_cost: 'Elliott must let E.T. go. The deepest love sometimes means letting go.',
    },
  },
  {
    title: 'Breaking Bad',
    year: '2008–2013',
    medium: 'tv',
    fields: {
      theme: 'This story proves that unchecked ego, disguised as noble intention, will destroy everything you claim to love.',
      protag_name: 'Walter White',
      protag_archetype: 'The Fallen Genius / Anti-Hero',
      protag_flaw: 'Monstrous pride — he\'d rather be feared than helped.',
      protag_misbelief: 'He believes he was cheated out of greatness, and that providing for his family justifies any crime.',
      a_goal: 'Must secure his family\'s financial future BEFORE his terminal cancer kills him or the DEA catches him.',
      antag_name: 'Hank Schrader',
      antag_want: 'To catch the drug lord "Heisenberg" — not knowing it\'s his own brother-in-law.',
      antag_belief: 'The law is the line between civilization and chaos. Criminals must be stopped.',
      antag_flaw: 'Blind spot for family loyalty (mirrors Walt\'s use of "family" as justification).',
      a1_want: 'Walt wants to leave money behind for his family before he dies.',
      a1_trigger: 'Terminal lung cancer diagnosis. He has months to live and nothing saved.',
      a1_inciting: 'Walt rides along on a DEA bust and sees the money in meth. He partners with Jesse.',
      a1_ponr: 'First cook. First lie to Skyler. He\'s now a criminal.',
      b1_flaws: 'Wounded pride from losing Gray Matter. Passive-aggressive resentment. Emasculation.',
      b1_contradiction: 'Says it\'s "for the family" but craves power and respect.',
      b1_block: 'His ego won\'t let him accept help (refuses Elliott and Gretchen\'s money).',
      c1_motivation: 'Hank is a good man doing his job. Gus Fring is a businessman protecting his empire.',
      c1_sympathize: 'Hank loves Walt. Gus lost his partner to the cartel. Both have genuine pain.',
      mid_choice: 'Walt lets Jane die — the right move to "protect Jesse" but actually to maintain control.',
      mid_change: 'Walt crosses from "doing bad things for good reasons" to "doing bad things because he likes it."',
      b3_revelation: '"I did it for me. I liked it. I was good at it. And I was alive."',
      den_truth: 'Empire-building under the guise of love is still destruction.',
      den_cost: 'Hank is dead. His family hates him. He dies alone in a meth lab.',
    },
  },
  {
    title: 'The Notebook',
    year: '2004',
    medium: 'film',
    fields: {
      theme: 'This story proves that true love endures beyond all obstacles — class, time, war, and even memory itself.',
      protag_name: 'Noah Calhoun',
      protag_archetype: 'The Devoted Romantic',
      protag_flaw: 'Obsessive devotion — holds on so tightly he almost loses himself.',
      protag_misbelief: 'He believes that if he loves hard enough, nothing can keep them apart — ignoring that Allie has her own journey.',
      a_goal: 'Must win Allie back BEFORE she marries Lon and their love story ends forever.',
      antag_name: 'Lon Hammond / Anne Hamilton (Allie\'s mother)',
      antag_want: 'Lon wants to marry Allie. Anne wants Allie to have a "proper" life away from poverty.',
      antag_belief: 'Stability and social standing matter more than passionate love.',
      antag_flaw: 'Prioritizing appearances over authentic feeling (mirrors Allie\'s struggle between duty and desire).',
      a1_inciting: 'Noah and Allie meet at a carnival. Instant, electric connection across class lines.',
      a1_ponr: 'They fall deeply in love over one summer. When it ends, they\'re torn apart by her parents.',
      b1_flaws: 'Noah is proud and stubborn. Allie is caught between pleasing her parents and following her heart.',
      b3_revelation: '"I thought love meant never letting go. The truth is love means choosing each other every single day, no matter what."',
      den_truth: 'Love isn\'t a feeling. It\'s a daily choice that outlasts everything — even memory.',
      den_cost: 'Years of separation. Noah\'s loneliness. Allie\'s Alzheimer\'s. But they chose each other until the very end.',
    },
  },
  {
    title: 'The X-Files',
    year: '1993–2002',
    medium: 'tv',
    fields: {
      theme: 'This story proves that the pursuit of truth is worth everything — even when the truth destroys your life.',
      protag_name: 'Fox Mulder',
      protag_archetype: 'The True Believer / Obsessed Seeker',
      protag_flaw: 'Monomaniacal obsession — he\'ll sacrifice everything and everyone for "the truth."',
      protag_misbelief: 'He believes finding proof of extraterrestrial life will heal the wound of his sister\'s abduction and give his life meaning.',
      a_goal: 'Must expose the government conspiracy to hide alien existence BEFORE the Syndicate buries the truth permanently.',
      antag_name: 'The Cigarette Smoking Man',
      antag_want: 'To manage the secret colonization deal with the aliens while maintaining human power structures.',
      antag_belief: 'He\'s protecting humanity by controlling the truth — the public can\'t handle it.',
      antag_flaw: 'Paternalistic control — believes only he knows what\'s best (mirrors Mulder\'s certainty that only he sees the truth).',
      a1_inciting: 'Scully is assigned to the X-Files to debunk Mulder\'s work. Instead, she encounters the unexplainable.',
      b1_flaws: 'Mulder\'s obsession isolates him. He trusts no one fully. He uses people.',
      b1_block: 'His inability to let go of his sister\'s abduction clouds his judgment on every case.',
    },
  },
  {
    title: '24',
    year: '2001–2010',
    medium: 'tv',
    fields: {
      theme: 'This story proves that protecting freedom requires sacrificing the very freedoms you\'re fighting to preserve.',
      protag_name: 'Jack Bauer',
      protag_archetype: 'The Dark Protector / Tragic Warrior',
      protag_flaw: 'Savior complex — believes only he can protect everyone, at any cost.',
      protag_misbelief: 'He believes the ends always justify the means, and that one man\'s suffering (his own) can save the world.',
      a_goal: 'Must stop the terrorist attack BEFORE the deadline hits and thousands die.',
      antag_name: 'Varies (Season 1: Victor Drazen)',
      antag_want: 'Revenge for the death of his family — to kill Palmer and destroy Bauer.',
      antag_belief: 'An eye for an eye. Bauer and the U.S. took everything from him.',
      antag_flaw: 'Vengeance blinds him to everything else — he\'ll burn the world for personal retribution.',
      a1_trigger: 'A credible threat against a presidential candidate. The clock starts ticking — literally.',
      b1_flaws: 'Jack\'s job has destroyed his marriage and his relationship with his daughter.',
      b1_contradiction: 'Wants to protect his family but his methods push them further away every season.',
    },
  },
  {
    title: 'Battlestar Galactica',
    year: '2004–2009',
    medium: 'tv',
    fields: {
      theme: 'This story proves that survival without humanity isn\'t survival at all — what makes us human is worth dying for.',
      protag_name: 'Admiral William Adama',
      protag_archetype: 'The Stoic Leader / Reluctant Commander',
      protag_flaw: 'Emotional rigidity — suppresses feeling to maintain command, at the cost of connection.',
      protag_misbelief: 'He believes military discipline and chain of command are sufficient to save humanity.',
      a_goal: 'Must lead the surviving fleet to Earth BEFORE the Cylons destroy what\'s left of humanity.',
      antag_name: 'The Cylons (Number One / Cavil)',
      antag_want: 'To prove machines are superior by destroying their creators.',
      antag_belief: 'Humanity is flawed and deserves extinction. Machines are the next evolution.',
      antag_flaw: 'Self-loathing disguised as superiority — Cavil hates that he was made in humanity\'s image.',
      a1_inciting: 'The Cylons launch a nuclear attack that destroys the Twelve Colonies. Billions die in hours.',
      b1_flaws: 'Adama\'s broken relationship with his son Lee. His grief over Zak. His inability to show vulnerability.',
      den_truth: 'Being human — flawed, messy, mortal — is the point. It\'s what the Cylons envied all along.',
    },
  },
  {
    title: 'Interview with the Vampire',
    year: '1994',
    medium: 'film',
    fields: {
      theme: 'This story proves that immortality without purpose is not a gift — it\'s a prison.',
      protag_name: 'Louis de Pointe du Lac',
      protag_archetype: 'The Reluctant Monster / Melancholic Outsider',
      protag_flaw: 'Paralyzing guilt — he can\'t accept what he is or fully commit to either humanity or vampirism.',
      protag_misbelief: 'He believes he can remain human while being a vampire — that he can have immortality without the cost.',
      a_goal: 'Must find meaning in his immortal existence BEFORE despair destroys him completely.',
      antag_name: 'Lestat de Lioncourt',
      antag_want: 'A companion — someone to share eternity with. He\'s terrified of being alone.',
      antag_belief: 'Vampirism is liberation. Embrace the predator. Guilt is weakness.',
      antag_flaw: 'His cruelty masks desperate loneliness (mirrors Louis\'s isolation).',
      a1_inciting: 'Lestat turns Louis into a vampire, trapping him in an existence he didn\'t fully choose.',
      b1_flaws: 'Louis clings to human morality in a predator\'s body. He starves himself feeding only on rats.',
      b1_block: 'His guilt prevents him from using his full power or finding any peace.',
    },
  },
  {
    title: 'The Avengers',
    year: '2012',
    medium: 'film',
    fields: {
      theme: 'This story proves that a team of broken individuals, united by a common cause, is stronger than any single force.',
      protag_name: 'Tony Stark / The Avengers (ensemble)',
      protag_archetype: 'The Arrogant Genius (Tony) / The Reluctant Team',
      protag_flaw: 'Ego and individualism — none of them can work together.',
      protag_misbelief: 'Each believes they\'re better off alone and that teamwork means compromise.',
      a_goal: 'Must stop Loki\'s alien invasion BEFORE Earth is conquered by the Chitauri army.',
      antag_name: 'Loki',
      antag_want: 'To rule Earth — to prove he\'s worthy of a throne, since Asgard rejected him.',
      antag_belief: 'Humans are made to be ruled. He\'s doing them a favor by providing order.',
      antag_flaw: 'Desperate need for validation — he wants to be loved but can only demand obedience.',
      a1_inciting: 'Loki steals the Tesseract and mind-controls Hawkeye. SHIELD activates the Avengers Initiative.',
      mid_choice: 'The team fractures on the Helicarrier — Loki\'s plan works. They\'re fighting each other.',
      mid_change: 'Coulson dies. The team has to decide if they\'ll come together or fall apart.',
      a3_confrontation: 'Battle of New York. Six heroes finally fighting as one unit.',
      a3_sacrificed: 'Tony carries the nuke through the portal — willing to die to save the city.',
      den_truth: 'Together, they\'re more than the sum of their parts. The team IS the superpower.',
    },
  },
  {
    title: 'Spider-Man: Homecoming',
    year: '2017',
    medium: 'film',
    fields: {
      theme: 'This story proves that being a hero isn\'t about the suit — it\'s about who you are without it.',
      protag_name: 'Peter Parker',
      protag_archetype: 'The Eager Rookie / Coming-of-Age Hero',
      protag_flaw: 'Desperation to prove himself — so eager to be an Avenger he ignores his own instincts.',
      protag_misbelief: 'He believes being a "real" hero means getting Tony Stark\'s approval and joining the Avengers.',
      a_goal: 'Must stop Vulture\'s weapons operation BEFORE alien tech floods the streets and someone dies.',
      antag_name: 'Adrian Toomes / The Vulture',
      antag_want: 'To provide for his family by selling salvaged alien weapons — the system screwed him, so he\'ll work outside it.',
      antag_belief: 'The rich and powerful (Stark, the government) take everything. He\'s just evening the score.',
      antag_flaw: 'Justifying crime through victimhood — he\'s become the very thing he resented.',
      a1_inciting: 'Peter encounters Toomes\' crew selling alien weapons and realizes there\'s a real threat happening under everyone\'s nose.',
      b1_flaws: 'Peter is immature, impulsive, and defines himself entirely by Spider-Man. He neglects school, friends, and his own identity.',
      b1_block: 'He can\'t see his own worth without the suit.',
      mid_choice: 'Peter ignores Tony\'s warning and goes after the ferry deal alone — nearly kills everyone on board.',
      mid_change: 'Tony takes the suit away. Peter has nothing.',
      b3_revelation: '"If I\'m nothing without the suit, then I shouldn\'t have it." Peter is the hero, not the tech.',
      a3_confrontation: 'Peter in his homemade suit vs. Vulture on the plane — no Avengers, no high-tech suit, just him.',
      den_truth: 'A hero is defined by character, not equipment or approval.',
    },
  },
  {
    title: 'Dune: Part Two',
    year: '2024',
    medium: 'film',
    fields: {
      theme: 'This story proves that prophecy is a weapon — and those who wield it become the very tyrants they sought to destroy.',
      protag_name: 'Paul Atreides',
      protag_archetype: 'The Reluctant Messiah / Tragic Emperor',
      protag_flaw: 'He sees the terrible future his choices will create but feels powerless to choose differently.',
      protag_misbelief: 'He believes he can ride the wave of religious prophecy without being consumed by it.',
      a_goal: 'Must defeat the Harkonnens and avenge his father BEFORE the Fremen are destroyed or the Imperium consolidates power.',
      antag_name: 'Feyd-Rautha Harkonnen / Emperor Shaddam IV',
      antag_want: 'Feyd wants glory and the throne. The Emperor wants to maintain his dynasty.',
      antag_belief: 'Power belongs to those strong enough to take it. The Atreides were a threat to order.',
      antag_flaw: 'Arrogance — they underestimate the desert and its people.',
      a1_trigger: 'Paul is stranded among the Fremen with no army, no title, and a bounty on his head.',
      mid_choice: 'Paul drinks the Water of Life, fully embracing the messianic role he knows will lead to galactic holy war.',
      mid_change: 'Paul stops resisting the prophecy. He becomes Muad\'Dib in full — and Chani sees him change.',
      b3_revelation: '"I thought I could control the prophecy. The truth is the prophecy controls me — and I\'m choosing it anyway."',
      den_truth: 'The hero and the tyrant can be the same person. Liberation and conquest are the same coin.',
      den_cost: 'Chani\'s love and trust. Paul\'s humanity. Holy war is now inevitable.',
    },
  },
  {
    title: 'Loki',
    year: '2021–2023',
    medium: 'tv',
    fields: {
      theme: 'This story proves that you can rewrite your story — but the cost of free will is bearing its weight alone.',
      protag_name: 'Loki Laufeyson',
      protag_archetype: 'The Trickster Redeemed',
      protag_flaw: 'Narcissism and fear of vulnerability — he betrays before he can be betrayed.',
      protag_misbelief: 'He believes he\'s destined to be alone and that power is the only thing that lasts.',
      a_goal: 'Must stop the destruction of the multiverse BEFORE all timelines collapse into chaos.',
      antag_name: 'He Who Remains / Victor Timely',
      antag_want: 'To prevent his dangerous variants from emerging by controlling all of time.',
      antag_belief: 'Free will leads to infinite war. Controlled destiny is the only safe path.',
      antag_flaw: 'God complex — believes only he can manage existence.',
      b1_flaws: 'Loki pushes everyone away. He\'s never had a genuine equal or friend.',
      b3_revelation: '"I thought being a god meant ruling. The truth is it means serving — holding the weight so others can be free."',
      a3_sacrificed: 'Loki takes the throne of time itself — alone, forever — so the multiverse can have free will.',
      den_truth: 'The ultimate power is sacrifice, not control.',
      den_cost: 'Loki sits alone at the end of time, holding every timeline together. The god of mischief becomes the god of stories.',
    },
  },
  {
    title: 'Furiosa: A Mad Max Saga',
    year: '2024',
    medium: 'film',
    fields: {
      theme: 'This story proves that vengeance cannot restore what was taken — only reclaiming your humanity can.',
      protag_name: 'Furiosa',
      protag_archetype: 'The Survivor Turned Avenger',
      protag_flaw: 'Consuming rage — her single-minded pursuit of revenge narrows her world to one target.',
      protag_misbelief: 'She believes killing Dementus will give her peace and return her to who she was.',
      a_goal: 'Must kill Dementus BEFORE his chaos spreads further and her humanity is fully extinguished.',
      antag_name: 'Dementus',
      antag_want: 'Power, territory, and meaning in a world that took everything from him.',
      antag_belief: 'If the world is meaningless, then taking whatever you want is the only rational response.',
      antag_flaw: 'Emptiness disguised as ambition — nothing he conquers fills the void.',
      a1_inciting: 'Young Furiosa is kidnapped from the Green Place. Her mother is killed trying to save her.',
      b1_block: 'Her rage makes her unable to trust or form connections — the very thing she needs to survive.',
      den_truth: 'Revenge doesn\'t heal. Building something new does.',
    },
  },
  {
    title: 'Heat',
    year: '1995',
    medium: 'film',
    fields: {
      theme: 'This story proves that obsession — whether with the law or the score — costs you everyone you love.',
      protag_name: 'Lt. Vincent Hanna',
      protag_archetype: 'The Obsessed Detective',
      protag_flaw: 'Addiction to the chase — the job IS his identity, destroying every relationship.',
      protag_misbelief: 'He believes he can have a personal life AND give everything to the job.',
      a_goal: 'Must catch Neil McCauley\'s crew BEFORE they pull their final heist and disappear.',
      antag_name: 'Neil McCauley',
      antag_want: 'One last score — enough to disappear forever with the woman he loves.',
      antag_belief: '"Don\'t let yourself get attached to anything you\'re not willing to walk out on in 30 seconds flat."',
      antag_flaw: 'Emotional isolation as a survival strategy — the same walls that protect him prevent him from truly living.',
      a1_inciting: 'McCauley\'s crew pulls a armored car heist. Hanna catches the case.',
      mid_choice: 'Hanna and McCauley sit across from each other at a diner — mutual respect, mutual warning.',
      mid_change: 'They see themselves in each other. Neither can walk away from what they are.',
      c3_flaw: 'McCauley breaks his own rule — he goes back for Waingro instead of escaping. His discipline cracks.',
      c3_mirror: 'Both men sacrifice love for obsession. Hanna wins because his obsession aligns with survival.',
      den_truth: 'You become what you do. And what both men do is chase — endlessly.',
      den_cost: 'McCauley dies holding Hanna\'s hand. Hanna saved the city but lost another marriage.',
    },
  },
  {
    title: 'The Usual Suspects',
    year: '1995',
    medium: 'film',
    fields: {
      theme: 'This story proves that the greatest trick evil pulls is convincing you it\'s powerless.',
      protag_name: 'Roger "Verbal" Kint',
      protag_archetype: 'The Unreliable Narrator / Hidden Mastermind',
      protag_flaw: 'Appears weak and harmless — but that IS the weapon.',
      protag_misbelief: '(The audience\'s misbelief): We believe Verbal is a victim caught up in events beyond his control.',
      a_goal: 'Must convince Agent Kujan of a false narrative BEFORE his true identity as Keyser Söze is discovered.',
      antag_name: 'Agent Dave Kujan (from Verbal\'s perspective)',
      antag_want: 'To solve the dock massacre and identify who organized it.',
      antag_belief: 'Keaton is the mastermind. Follow the logic. Trust the evidence.',
      antag_flaw: 'Arrogance — he\'s so sure he\'s smarter that he accepts the story Verbal feeds him.',
      a1_inciting: 'Five criminals are brought together in a police lineup. A job is proposed.',
      a3_confrontation: 'Verbal walks out of the police station. Kujan realizes the entire story was fabricated.',
      den_truth: '"The greatest trick the devil ever pulled was convincing the world he didn\'t exist."',
      den_cost: 'Everyone is dead. Söze walks free. And the audience realizes they were played too.',
    },
  },
  {
    title: 'Star Wars: A New Hope',
    year: '1977',
    medium: 'film',
    fields: {
      theme: 'This story proves that even the smallest person from the farthest corner of the galaxy can change everything — if they trust in something greater than themselves.',
      protag_name: 'Luke Skywalker',
      protag_archetype: 'The Farm Boy Hero / Chosen One',
      protag_flaw: 'Naiveté and restlessness — wants adventure but isn\'t ready for its costs.',
      protag_misbelief: 'He believes adventure and heroism are glamorous, and that his destiny is somewhere "out there."',
      a_goal: 'Must deliver the Death Star plans to the Rebellion and destroy the station BEFORE the Empire wipes out the Rebel base.',
      antag_name: 'Darth Vader / Grand Moff Tarkin',
      antag_want: 'To crush the Rebellion and rule the galaxy through fear.',
      antag_belief: 'Order through power. The Force is less important than the technological terror of the Death Star.',
      antag_flaw: 'Overreliance on technology and underestimation of faith.',
      a1_inciting: 'Luke discovers Leia\'s message in R2-D2: "Help me, Obi-Wan Kenobi."',
      a1_ponr: 'Owen and Beru are killed. Luke has nothing left on Tatooine.',
      b3_revelation: '"Use the Force, Luke. Let go." Trust replaces self-reliance.',
      a3_confrontation: 'The trench run on the Death Star — one shot, guided by the Force.',
      den_truth: 'Faith in the unseen (the Force) triumphs over the visible (the Death Star).',
    },
  },
  {
    title: 'Return of the Jedi',
    year: '1983',
    medium: 'film',
    fields: {
      theme: 'This story proves that redemption is always possible — even for those who\'ve committed the greatest evil — if someone believes in them.',
      protag_name: 'Luke Skywalker',
      protag_archetype: 'The Compassionate Warrior',
      protag_flaw: 'Temptation toward anger — the Dark Side pulls at him through his love for his friends.',
      protag_misbelief: 'He initially believes he must fight and defeat his father to end the Empire.',
      a_goal: 'Must defeat the Emperor and destroy the second Death Star BEFORE the Rebellion is annihilated.',
      antag_name: 'Emperor Palpatine',
      antag_want: 'To turn Luke to the Dark Side and secure his empire for eternity.',
      antag_belief: 'The Dark Side is natural. Compassion is weakness. Power is everything.',
      antag_flaw: 'Cannot comprehend love or self-sacrifice — it\'s literally beyond his understanding.',
      mid_choice: 'Luke surrenders to Vader — walking into the trap — because he believes his father can be saved.',
      b3_revelation: '"I thought I had to destroy Vader. The truth is I have to save Anakin."',
      a3_sacrificed: 'Luke throws away his lightsaber — refusing to fight. He\'d rather die than become his father.',
      c3_flaw: 'Palpatine cannot conceive of Vader\'s love for his son. It\'s his blind spot.',
      den_truth: 'Love is stronger than the Dark Side. A son\'s faith redeemed a monster.',
    },
  },
  {
    title: 'Bridesmaids',
    year: '2011',
    medium: 'film',
    fields: {
      theme: 'This story proves that you can\'t be a good friend — or a good anything — until you stop sabotaging yourself.',
      protag_name: 'Annie Walker',
      protag_archetype: 'The Underdog / Self-Saboteur',
      protag_flaw: 'Self-destruction disguised as selflessness — she\'s so busy failing that she can\'t let anyone help.',
      protag_misbelief: 'She believes she\'s fundamentally broken and unworthy of good things, so she pushes them away.',
      a_goal: 'Must be the perfect maid of honor for Lillian BEFORE Helen replaces her entirely.',
      antag_name: 'Helen Harris III',
      antag_want: 'To be Lillian\'s best friend — because she\'s lonely and needs to control relationships to feel valued.',
      antag_belief: 'Money, taste, and perfection make you worthy of love.',
      antag_flaw: 'Uses wealth to buy intimacy because she doesn\'t believe she\'s lovable on her own (mirrors Annie).',
      a1_inciting: 'Lillian announces her engagement. Annie is maid of honor — but her life is falling apart.',
      b1_flaws: 'Failed bakery, toxic relationship with Ted, broke, living with weird roommates.',
      b1_contradiction: 'Wants to be there for Lillian but keeps making every event about her own spiral.',
      mid_choice: 'Annie\'s jealousy of Helen causes the bridal shower disaster — she completely melts down.',
      b3_revelation: '"I thought I wasn\'t worth anything. The truth is I\'ve been choosing to fail because success scares me."',
      a3_confrontation: 'Annie bakes a humble, heartfelt cake, finds Lillian, and saves the wedding — by being herself.',
      den_truth: 'Your worst enemy is you. And your best friend deserves you at your best.',
    },
  },
  {
    title: 'Back to the Future',
    year: '1985',
    medium: 'film',
    fields: {
      theme: 'This story proves that your destiny isn\'t inherited — you can rewrite your family\'s story if you have the courage to act.',
      protag_name: 'Marty McFly',
      protag_archetype: 'The Everyday Teen / Accidental Time Traveler',
      protag_flaw: 'Can\'t stand being called "chicken" — his ego makes him reckless when challenged.',
      protag_misbelief: 'He believes his family is destined to be losers and there\'s nothing he can do about it.',
      a_goal: 'Must get his parents together at the Enchantment Under the Sea dance BEFORE he\'s erased from existence, then get back to 1985.',
      antag_name: 'Biff Tannen',
      antag_want: 'To dominate George McFly, own Lorraine, and bully his way through life.',
      antag_belief: 'Strength is taking what you want. Weakness deserves to be punished.',
      antag_flaw: 'Pure entitlement — he\'s never had to earn anything.',
      a1_inciting: 'The DeLorean sends Marty to 1955. His mom falls for HIM instead of his dad.',
      a1_ponr: 'Marty\'s hand starts fading in the photograph. Clock is ticking — literally.',
      b1_flaws: 'Marty has internalized his family\'s loser identity. He\'s embarrassed by his parents.',
      mid_choice: 'Marty decides to teach George to stand up for himself — changing the family timeline forever.',
      a3_confrontation: 'George punches Biff. The photograph restores. Lightning strikes the clock tower.',
      den_truth: 'One act of courage ripples through generations. Your family\'s future is not set.',
      den_cost: 'Marty risked his own existence. But he gained a family worth coming home to.',
    },
  },
  {
    title: 'Sinners',
    year: '2025',
    medium: 'film',
    fields: {
      theme: 'This story proves that running from your sins doesn\'t save you — you have to face the darkness inside before you can fight the darkness outside.',
      protag_name: 'Smoke & Stack (twin brothers)',
      protag_archetype: 'The Prodigal Sons / Reluctant Warriors',
      protag_flaw: 'Running from their past — they left violence behind but brought the guilt with them.',
      protag_misbelief: 'They believe starting fresh in the South erases what they did up North.',
      a_goal: 'Must protect their juke joint and community BEFORE the vampires consume everything they\'ve built.',
      antag_name: 'Remmick (The Vampire)',
      antag_want: 'To consume and convert — not just blood, but culture, music, and soul.',
      antag_belief: 'Immortality is the ultimate freedom. Human attachment is weakness.',
      antag_flaw: 'Cannot create, only consume — mirrors colonialism\'s relationship with Black culture.',
      a1_inciting: 'The twins open a juke joint in Jim Crow Mississippi. A stranger arrives who isn\'t what he seems.',
      b1_block: 'Their violent past makes them distrust help and resist forming real community.',
    },
  },
  {
    title: 'F1',
    year: '2025',
    medium: 'film',
    fields: {
      theme: 'This story proves that second chances aren\'t given — they\'re taken, one lap at a time.',
      protag_name: 'Sonny Hayes',
      protag_archetype: 'The Comeback Kid / Haunted Racer',
      protag_flaw: 'Survivor\'s guilt from a devastating crash that ended his career and killed someone.',
      protag_misbelief: 'He believes he doesn\'t deserve to race again — that the track took everything and he should stay away.',
      a_goal: 'Must prove himself as an F1 driver again BEFORE age and doubt close the window forever.',
      antag_name: 'Joshua Pearce (rival driver / team politics)',
      antag_want: 'To protect his position — he doesn\'t want some washed-up comeback story stealing his seat.',
      antag_belief: 'Racing is for the young and fearless. Nostalgia doesn\'t win championships.',
      antag_flaw: 'Raw talent without wisdom — he\'s fast but reckless.',
      a1_trigger: 'An APEX team owner gives Sonny an impossible offer: one last shot at the back of the grid.',
      b1_flaws: 'Sonny flinches in braking zones. The trauma lives in his body, not just his mind.',
    },
  },
];

/**
 * Get examples for a specific field key across all films
 */
export function getExamplesForField(fieldKey: string): { title: string; year: string; medium: 'film' | 'tv'; value: string }[] {
  return filmExamples
    .filter(f => f.fields[fieldKey])
    .map(f => ({
      title: f.title,
      year: f.year,
      medium: f.medium,
      value: f.fields[fieldKey],
    }));
}

/**
 * Get full story DNA templates (films that have at least 8 core DNA fields filled)
 */
export function getFullTemplates(): FilmExample[] {
  const coreKeys = ['theme', 'protag_name', 'protag_flaw', 'protag_misbelief', 'a_goal', 'antag_name', 'antag_want', 'antag_flaw'];
  return filmExamples.filter(f => {
    const filled = coreKeys.filter(k => f.fields[k]).length;
    return filled >= 6;
  });
}
