import { Link } from 'react-router-dom';
import { LegalFooter } from '@/components/LegalFooter';
import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';

const AcceptableUsePolicy = () => {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="max-w-4xl mx-auto px-4 py-12">
        <Link to="/">
          <Button variant="ghost" size="sm" className="mb-6">
            <ArrowLeft className="w-4 h-4 mr-2" /> Back to Home
          </Button>
        </Link>

        <h1 className="text-3xl font-bold mb-2 font-mono tracking-tight">Acceptable Use Policy</h1>
        <p className="text-muted-foreground mb-8">Last updated: March 9, 2026 | Includes AI-Specific Governance (ISO 42001)</p>

        <div className="prose prose-invert max-w-none space-y-6 text-sm text-foreground/90 leading-relaxed">

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">1. Purpose</h2>
            <p>This Acceptable Use Policy ("AUP") governs the use of the Celsius platform and its AI-powered features. This policy is designed to ensure responsible, ethical, and lawful use of the Service, with specific provisions for AI-generated content in accordance with ISO 42001:2023 (Artificial Intelligence Management Systems).</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">2. General Acceptable Use</h2>
            <p>You may use the Service to: create, edit, and manage comic and graphic novel projects; generate character designs and story art using AI tools; collaborate with other users on creative projects; format and organize scripts and manuscripts; and manage character libraries and story continuity.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">3. Prohibited Uses</h2>
            <p>You may NOT use the Service to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Generate content depicting child sexual abuse material (CSAM) or exploitation of minors</li>
              <li>Create deepfakes or non-consensual intimate imagery of real individuals</li>
              <li>Generate content that promotes terrorism, extreme violence, or incites hatred against protected groups</li>
              <li>Produce fraudulent identity documents, currency, or official communications</li>
              <li>Create content intended to harass, threaten, stalk, or intimidate specific individuals</li>
              <li>Generate misleading content intended to deceive the public or manipulate elections</li>
              <li>Circumvent content safety filters or attempt to extract training data from AI models</li>
              <li>Use the Service for mass surveillance or to infringe upon individuals' reasonable expectation of privacy</li>
              <li>Violate any applicable laws, regulations, or third-party rights</li>
              <li>Conduct or facilitate any activity that is harmful, fraudulent, or deceptive</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">4. AI-Specific Guidelines (ISO 42001)</h2>
            <p>In accordance with our ISO 42001 certification for AI management systems:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Transparency:</strong> Content generated by AI must not be represented as human-created work without disclosure, particularly in journalistic, academic, or legal contexts.</li>
              <li><strong>Accuracy:</strong> You are responsible for reviewing all AI-generated content for accuracy and appropriateness before publishing or distributing.</li>
              <li><strong>Bias Awareness:</strong> AI models may reflect biases present in training data. Users should critically evaluate generated content for stereotypes or biased representations.</li>
              <li><strong>Intellectual Property:</strong> Do not use the AI features to intentionally replicate copyrighted works, trademarks, or the distinctive artistic style of identifiable living artists without authorization.</li>
              <li><strong>Human Oversight:</strong> AI features are tools to assist creativity. Final editorial decisions and responsibility for published content rest with the user.</li>
              <li><strong>Feedback Loop:</strong> Users are encouraged to report problematic AI outputs through the in-app reporting mechanism to help improve model safety.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">5. Content Standards</h2>
            <p>User Content and AI-generated content must comply with the following standards: (a) must not infringe intellectual property rights of third parties; (b) must not contain unlawful, defamatory, or obscene material that violates applicable law; (c) must not impersonate real individuals without their consent; (d) must comply with applicable advertising and disclosure regulations if used commercially; and (e) must include appropriate content warnings when depicting graphic violence or mature themes.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">6. Enforcement</h2>
            <p>Violations of this AUP may result in: (a) warning notification; (b) temporary suspension of access to AI features; (c) temporary or permanent suspension of account; (d) removal of offending content; and (e) reporting to law enforcement where legally required. We review reported violations and take action proportionate to the severity and frequency of violations.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">7. Reporting Violations</h2>
            <p>To report a violation of this policy, contact abuse@celsius.io with details including: the nature of the violation, any relevant URLs or content identifiers, and your contact information for follow-up. We investigate all reports within 48 business hours.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">8. Contact</h2>
            <p>For questions about this Acceptable Use Policy: legal@celsius.io</p>
          </section>

        </div>
      </div>
      <LegalFooter />
    </div>
  );
};

export default AcceptableUsePolicy;
